# Generated by Django 5.1.2 on 2024-10-23 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='exemplo@email.com', max_length=254)),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter apenas dígitos.', regex='^\\d{10,15}$')])),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=20)),
                ('resumo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='nome completo', max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não-binário', 'Não-binário'), ('Outro', 'Outro'), ('Prefiro não dizer', 'Prefiro não dizer')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
