# Generated by Django 5.1.2 on 2024-10-24 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='pessoa',
            field=models.ManyToManyField(related_name='experiencias', to='form.pessoa'),
        ),
        migrations.AddField(
            model_name='formacao',
            name='pessoa',
            field=models.ManyToManyField(related_name='formacoes', to='form.pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='form.contato'),
        ),
    ]
