# Generated by Django 5.1.2 on 2024-10-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_pessoa_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='endereco',
            new_name='contato',
        ),
    ]
