# Generated by Django 5.1.2 on 2024-10-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_contato_email_alter_contato_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='cidade',
            field=models.CharField(default='desconhecido', max_length=80),
        ),
    ]
