# Generated by Django 5.1.2 on 2024-10-27 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_contato_email_alter_contato_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cidade',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(help_text='exemplo@email.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter apenas dígitos.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='resumo',
            field=models.TextField(max_length=200),
        ),
    ]
