# Generated by Django 5.1.2 on 2024-10-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_contato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='contato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='form.contato'),
        ),
    ]
