# Generated by Django 5.1.2 on 2024-10-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_pessoa_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='form.experiencia')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='form.pessoa')),
            ],
        ),
    ]
