# Generated by Django 5.1.2 on 2024-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_pessoaexperiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='pessoa',
        ),
    ]
