# Generated by Django 5.1.2 on 2024-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_remove_experiencia_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='pessoa',
            field=models.ManyToManyField(related_name='experiencias', to='form.pessoa'),
        ),
        migrations.DeleteModel(
            name='PessoaExperiencia',
        ),
    ]
