# Generated by Django 5.1.2 on 2024-10-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_experiencia_pessoa_delete_pessoaexperiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='resumo',
            field=models.TextField(max_length=1000),
        ),
    ]
